# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-json
  - id: check-toml
  - id: check-xml
  - id: check-ast
  - id: check-symlinks
  - id: check-vcs-permalinks
  - id: debug-statements
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: detect-private-key
  - id: mixed-line-ending
  - id: pretty-format-json
    args: [--autofix]
  - id: requirements-txt-fixer

    #- repo: https://github.com/pycqa/isort
    #  rev: 6.0.1
    #  hooks:
    #  - id: isort
    #    name: isort (python)

- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.1
  hooks:
  - id: pyupgrade
    args: [--keep-percent-format]

- repo: https://github.com/bwhmather/ssort
  rev: 0.14.0
  hooks:
  - id: ssort

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.8
  hooks:
  - id: ruff
    args: [--preview, --fix]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.16.0
  hooks:
  - id: mypy
    args: [--ignore-missing-imports]
